<RV>:
    viewclass: 'Label'

    RecycleBoxLayout:
        default_size: None, dp(40)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'

<FloatLayout>
    canvas.before:
        BorderImage:
            source: 'resources/background.png'
            pos: self.pos
            size: self.size

    Button:
        text: 'Dequarantine all...'
        size_hint: 0.2, 0.1
        pos_hint: {'x': 0.4 ,'y': 0.9}